// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';  
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {          
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanNyuLtPRBsir8XQnU1elnolFXvcqNY4',
    appId: '1:676780590188:web:56b2f2b7e90b7054490449',
    messagingSenderId: '676780590188',
    projectId: 'mole-master-new-oo',
    authDomain: 'mole-master-new-oo.firebaseapp.com',
    storageBucket: 'mole-master-new-oo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-FxuvNuVv3k4GsTsWvLyhVzgU5wZcN4',
    appId: '1:676780590188:android:c91362aa23494000490449',
    messagingSenderId: '676780590188',
    projectId: 'mole-master-new-oo',
    storageBucket: 'mole-master-new-oo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrcqc9xz6xYxUOML7Wd62kwjdGJsgW-U',
    appId: '1:676780590188:ios:e1483f7be50b3265490449',
    messagingSenderId: '676780590188',
    projectId: 'mole-master-new-oo',
    storageBucket: 'mole-master-new-oo.firebasestorage.app',
    iosBundleId: 'com.example.moleMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrcqc9xz6xYxUOML7Wd62kwjdGJsgW-U',
    appId: '1:676780590188:ios:e1483f7be50b3265490449',
    messagingSenderId: '676780590188',
    projectId: 'mole-master-new-oo',
    storageBucket: 'mole-master-new-oo.firebasestorage.app',
    iosBundleId: 'com.example.moleMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDanNyuLtPRBsir8XQnU1elnolFXvcqNY4',
    appId: '1:676780590188:web:b185f9ca9e737df0490449',
    messagingSenderId: '676780590188',
    projectId: 'mole-master-new-oo',
    authDomain: 'mole-master-new-oo.firebaseapp.com',
    storageBucket: 'mole-master-new-oo.firebasestorage.app',
  );

}